# This file is auto-generated by collect_imports.py. DO NOT EDIT.
# It contains all raw import lines from plugins and tools.

print('--- Loading hidden imports for PyInstaller ---')

try:
    from ctypes import wintypes
    from plugin_base import BasePlugin
    from pywinauto import Application
    from pywinauto.application import Application
    from pywinauto.findwindows import ElementNotFoundError
    from typing import Dict, Any
    import configparser
    import ctypes
    import cv2
    import driver_360_autoins
    import getpass
    import importlib
    import math
    import numpy as np
    import os
    import ps_plugin_register
    import psutil
    import pyautogui
    import qi_register
    import random
    import re
    import subprocess
    import sys
    import time
    import tkinter as tk
    import traceback
    import win32clipboard
    import win32con
    import win32gui
    import winreg
    import xunjiepdf_register
except ImportError:
    # This block is expected to have errors at runtime if a library
    # is not installed, but it serves its purpose for PyInstaller's analysis.
    pass
