import re
from pathlib import Path
import sys

# --- 配置 ---
ROOT_DIR = Path(__file__).parent
DIRS_TO_SCAN = [
    ROOT_DIR / "plugins",
    ROOT_DIR / "plugins" / "tools",
    ROOT_DIR / "plugins_test",
]
OUTPUT_FILE = ROOT_DIR / "_hidden_imports.py"


def run():
    """
    扫描.py文件，原样提取所有顶层的import和from语句，
    去重后直接写入到一个文件中。
    """
    all_import_lines = set()

    # 【核心修改】正则表达式现在匹配以 'import' 或 'from' 开头的整行
    import_pattern = re.compile(r"^\s*(?:import|from)\s+.*")

    print("--- [Dependency Collector] Starting scan (raw line copy)...")
    for scan_dir in DIRS_TO_SCAN:
        if not scan_dir.exists():
            print(f"--- [WARNING] Directory not found, skipping: {scan_dir}")
            continue

        print(f"--- [INFO] Scanning directory: {scan_dir}")
        for py_file in scan_dir.glob("*.py"):
            try:
                with open(py_file, 'r', encoding='utf-8') as f:
                    for line in f:
                        # 逐行匹配
                        if import_pattern.match(line):
                            # 去除行尾的换行符和两边的空格
                            clean_line = line.strip()
                            # 忽略空的或只有注释的行
                            if clean_line and not clean_line.startswith('#'):
                                all_import_lines.add(clean_line)
            except Exception as e:
                print(f"  - [ERROR] Failed to read or process {py_file.name}: {e}")

    print("--- [INFO] Scan complete.")
    if not all_import_lines:
        print("--- [INFO] No import lines found to process.")
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write("# Auto-generated. No hidden imports found.\n")
        return

    # 按字母顺序排序，让输出文件更整洁
    sorted_import_lines = sorted(list(all_import_lines))
    print(f"--- [INFO] Found {len(sorted_import_lines)} unique import lines.")

    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write("# This file is auto-generated by collect_imports.py. DO NOT EDIT.\n")
            f.write("# It contains all raw import lines from plugins and tools.\n\n")
            f.write("print('--- Loading hidden imports for PyInstaller ---')\n\n")
            f.write("try:\n")
            # 【核心修改】将收集到的原始行直接写入 try 块
            for line in sorted_import_lines:
                f.write(f"    {line}\n")
            f.write("except ImportError:\n")
            f.write("    # This block is expected to have errors at runtime if a library\n")
            f.write("    # is not installed, but it serves its purpose for PyInstaller's analysis.\n")
            f.write("    pass\n")
        print(f"--- [SUCCESS] Dependencies successfully written to: {OUTPUT_FILE}")
    except Exception as e:
        print(f"--- [ERROR] Failed to write to output file {OUTPUT_FILE}: {e}")
        sys.exit(1)


if __name__ == "__main__":
    run()